version: "3.8"

configs:
  nginx_conf:
    file: ./qs-http-listener-bot-nginx.conf    # <-- must point to a real file

services:
  proxy:
    image: nginx:stable
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    ports:
      - "54255:80"
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 0    # unlimited retries

  bot:
    image: g4-http-qs-listener-bot:latest
    volumes:
      - C:/g4-bots-volume:/bots
    environment:
      BOT_NAME:            "g4-http-listener-bot"
      CALLBACK_INGRESS:    "http://host.docker.internal:54255"
      DRIVER_BINARIES:     "http://host.docker.internal:4444/wd/hub"
      ENTRY_POINT_INGRESS: "http://host.docker.internal:54255"
      HUB_URI:             "http://host.docker.internal:9944"
      TOKEN: >-
        3xezq5Yc33laNOPNP8yCsK33vQcQZ87E/zyLNNscYNeqvKTHAm9C3wAEDQV7X9+
        fuuHPhafDNXbSFgsbKmCncCKm7DRE5A6JtFSd90DNujujbQ3vLG4/4uSVCR76Z6VguIDSvRZ/
        pJTHCzBc9NNI/eb5fLHcjXyYrilm9NC7VTD/HOlgGC5CL+oFhHoR8s10YuI9QpRioZbyDHy
        sFumpAAv3/PG/p/QBKNoQpjtsUgMytrnqr3m1bgyXITG0u5AUR2VpZLCXQO6MxU7kwLwvdN
        GXUDfajBVT29KyjXUEWN9dK0R38XmgZFQ7orkKfN2z0x2SMfC5mvTDM6as+/kYWFAvpqOZD
        hZ95sgQWp/zGig=
    expose:
      - "9213"
      - "9123"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s
    networks:
      - backend

networks:
  backend:
    driver: overlay
